#!/usr/bin/env ruby

$script = <<-'SCRIPT'
set -xe
export DEBIAN_FRONTEND=noninteractive
apt-get -qq update

# Install dependencies
apt-get -qq install -y \
        git \
        cmake \
        g++ \
        binutils-dev \
        libc6-dev-i386

SCRIPT

$shell = <<-'SHELL'
# Clone and build LLVM for ct_choose
git clone https://github.com/lmrs2/llvm.git -b ctchoose_38 --single-branch --depth 1
cd llvm/tools
git clone https://github.com/lmrs2/clang.git -b ctchoose_38 --single-branch --depth 1
cd ..
mkdir build
cd build
cmake -DLLVM_BINUTILS_INCDIR=/usr/include -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD="X86" ../
cmake --build .
sudo make install

SHELL

$msg = <<~MSG
---------------------------------------------
LLVM has been installed.

Get ssh access to the VM with:
     vagrant ssh

The files in the current directory can be found
in the /vagrant directory
---------------------------------------------
MSG

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, name: "Install dependencies", inline: $script

  config.vm.provision "shell", name: "Install lmrs2 ctchoose_38", inline: $shell

  config.vm.post_up_message = $msg

  config.vm.provider "virtualbox" do |v|
        v.name = "What you get is what you C - ct_choose"
        v.memory = 4096
        v.cpus = 2
  end
end
